// Stable public contract. Internal modules import their dependencies directly.
export {
  ENTITY_TYPES,
  ENTITY_TYPE_DIRECTORIES,
  RELATION_TYPES,
  SYMMETRIC_RELATION_TYPES,
  LOCALES,
  DEPTHS,
  type EntityType,
  type Locale,
  type Depth,
  entityIdPattern,
  entityIdSchema,
  sourceIdSchema,
  mediaIdSchema,
  narrativeIdSchema,
  learningPathIdSchema,
} from "./model/common";
export {
  CONTENT_BLOCK_TYPES,
  CAVEAT_VARIANTS,
  type ContentBlockType,
  type CaveatVariant,
  type ContentTextNode,
  type ContentInlineCodeNode,
  type ContentEntityLinkNode,
  type ContentCitationNode,
  type ContentInlineContainerNode,
  type ContentLinkNode,
  type ContentBreakNode,
  type ContentInlineNode,
  type ContentParagraphNode,
  type ContentHeadingNode,
  type ContentListItemNode,
  type ContentListNode,
  type ContentBlockquoteNode,
  type ContentTableNode,
  type ContentBlockNode,
  type ContentBlock,
  type ContentDocument,
} from "./model/documents";
export {
  relationSchema,
  assertionSchema,
  entityPresentationSchema,
  entitySchema,
  type Entity,
  type EntityPresentation,
  type Relation,
  entityPresentationMode,
} from "./model/entities";
export { narrativeSchema, type Narrative } from "./model/narratives";
export {
  CURRICULUM_LEVELS,
  type CurriculumLevel,
  learningPathSchema,
  type LearningPath,
} from "./model/learning-paths";
export {
  MEDIA_KINDS,
  MEDIA_ROLES,
  MEDIA_RIGHTS_STATUSES,
  type MediaKind,
  type MediaRole,
  sourceSchema,
  mediaAssetSchema,
  type Source,
  type MediaAsset,
} from "./model/provenance";
export {
  REGION_OVERVIEW_DIMENSIONS,
  APPELLATION_OVERVIEW_DIMENSIONS,
  GRAPE_OVERVIEW_DIMENSIONS,
  CONCEPT_SYSTEM_OVERVIEW_DIMENSIONS,
  CONCEPT_FOCUSED_OVERVIEW_DIMENSIONS,
  CONTENT_PLAN_DIMENSIONS,
  CONTENT_PLAN_SECTION_HEADINGS,
  contentPlanSchema,
  type ContentPlan,
} from "./model/content-plans";
export {
  type ResolvedRelation,
  type NarrativeMention,
  type SearchPassage,
  type EntitySearchIndexEntry,
  type NarrativeSearchIndexEntry,
  type SearchIndexEntry,
  type GeneratedEntity,
  type GeneratedNarrative,
  type LearningPathMembership,
  type GeneratedKnowledgeBase,
} from "./model/generated";
